### PR TITLE
models

### PR DESCRIPTION
**Pull request by htoss**

### CODE REVIEW

**Comment by abench** [comment]
Well done, but remove  (or move table.stl file from root directory), please.

**Comment by abench** [comment]
Models were placed into correct place, table.stl deleted from root directory. I accept merge

**Review by abench — APPROVED** [review]
Models were placed into correct place, table.stl deleted from root directory. I accept merge

**Comment by abench** [comment]
@ldemk merge files, please.

**Comment by ldemk** [comment]
Merged #6 into master

**Pull request merged**
